In [ ]:
#4

import numpy as np

arr= np.array([100,200,300,400,500,600])

arr1=np.array(arr[:3])
arr2=np.array(arr[3:])
arr2=np.append(arr2,700)
print(arr,arr1,arr2)


[100 200 300 400 500 600] [100 200 300] [400 500 600 700]


In [ ]:
#1
arr= np.array([0,1,2,3,4,5,6,7,8,9,10,11])
new=arr.reshape(3,4)
print(new[1],new[2,3])

[4 5 6 7] 11


In [ ]:
#2
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2))
print(arr3[1:6])

[2 3 4 5 6]


In [ ]:
#3
arr=np.array([10,20,30,40,50])
arr2=arr.copy()
arr2=np.delete(arr2,2)
print(arr)
print(arr2)

[10 20 30 40 50]
[10 20 40 50]
